[OKR] SQL Handbook
infinum/rails-handbook pull request #142
Opened 2022-03-15 11:50 UTC by PetarCurkovic

Task [#415](https://app.productive.io/1-infinum/task/2044837)

#### Aim

Add list of SQL query examples for our SQL catalogue, with some interesting SQL topics.

#### Solution

* Added query examples for SQL handbook
* Added General info, Tips&Tricks, and Indexes chapters

2022-03-17 06:05 UTC, nikajukic reviewed
Great job @PetarCurkovic!! 🎉 👌

2022-03-17 06:05 UTC, nikajukic commented on Databases/SQL/Tips & Tricks.md
> +## VIEWs
I'd maybe mention few more things here:

- you can use a view as an ActiveRecord model (with example)
- scenic gem for managing views?
- are materialized views a way to go if you have a lot of inserts (you'd need to refresh it constantly)
- tips on when to use which view?

2022-03-17 09:50 UTC, Benaaaaa commented
Hey, just a heads up, in both **indexes** and **tips & tricks** chapters in the beta version of the [handbook](https://beta.infinum.com/handbook/rails/databases/sql/tips-and-tricks) the bullet points are not being rendered properly. I tried investigating why is that but don't know much markdown and it doesn't make sense at the moment why is it like that

2022-03-17 09:52 UTC, PetarCurkovic commented
> Hey, just a heads up, in both **indexes** and **tips & tricks** chapters in the beta version of the [handbook](https://beta.infinum.com/handbook/rails/databases/sql/tips-and-tricks) the bullet points are not being rendered properly. I tried investigating why is that but don't know much markdown and it doesn't make sense at the moment why is it like that

@Benaaaaa thx, I already fixed that (will be pushed soon)!
There is a missing new line between the text and bullet list.

2022-03-17 10:21 UTC, cilim reviewed
Great work! 👏 🔥 🙂

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/General.md
> +When you work on backend systems, you will always have some kind of data storage where you will persist the application data.
```suggestion
Working on backend systems almost always necessitates the use of a database where application data can be stored.
```

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/General.md
> +The majority of our applications, use a relational database as a data storage solution.
```suggestion
The majority of our applications use a relational database as a data storage solution.
```

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/General.md
> +To be able to communicate with your database, you need to use SQL.
```suggestion
SQL (structured query language) is the tool for communicating with the database.
```

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/General.md
> +To be able to **solve complex problems** and to get **better understanding** of how the ORM works, here are some query examples and advice to help you with that!
```suggestion
To be able to **solve complex problems** and to get **better understanding** of how the ORM works, here are some query examples and advices to help you with that!
```

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/General.md
> +SQL is correctly pronounced "ess-cue-ell", not "see-quell".
👏 👏 👏

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/General.md
> +  * [Postico](https://eggerapps.at/postico/) (only for Mac - we have a full version license)
```suggestion
  * [Postico](https://eggerapps.at/postico/) (only for Mac - we have a full version license that you can acquire from your team lead)
```

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/Indexes.md
> +  * majority of rows are getting fetched as part of the SQL query
```suggestion
Possible situations:
  
  * majority of rows are getting fetched as part of the SQL query
```

I believe a new row is missing here for bullet formatting

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/Tips & Tricks.md
> +> You can add indexes to materialized views!
```suggestion
> You can add indexes to materialized views, but not plain database views.
```

2022-03-17 10:21 UTC, cilim commented on Databases/SQL/Tips & Tricks.md
> +But, sometimes, PostGIS might be overkill for your use case - read more here [why you (probably) don't need PostGIS](https://blog.rebased.pl/2020/04/07/why-you-probably-dont-need-postgis.html).
```suggestion
PostGIS might be overkill in some scenarios - read more here [why you (probably) don't need PostGIS](https://blog.rebased.pl/2020/04/07/why-you-probably-dont-need-postgis.html).
```

2022-03-17 10:49 UTC, Benaaaaa commented
One proposal on the query examples: the SQL solution process is never top-down and so just reading the solution won't give us much info on how to maybe approach some problems. If it is possible could there be added a Solving steps section on what things were first solved and how the solution came to be? Sort of like you did it in the backend talks. For example just reading the solutions that are using the window function and PG documentation I am still having a hard time understanding how it exactly works, but when it was introduced on how it worked in the backend talks, it was much more clearer.

2022-03-17 15:34 UTC, cukoreva requested changes

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Query Examples/05 - CSV.md
> +You have to import new users from large CSV file.
```suggestion
You have to import new users from a large CSV file.
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Query Examples/05 - CSV.md
> +You have to export users with surname “Smith” to CSV.
```suggestion
You have to export users with the surname “Smith” to CSV.
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Query Examples/08 - UPDATE with subquery.md
> +Write a query that will update current posts table data to the suggested structure.
```suggestion
Write a query that will update the current posts table data to the suggested structure.
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +You should avoid multiple DB queries from the application if you can fetch needed data in a single query. Always check what queries are executed in your (Rails) log.
```suggestion
You should avoid multiple DB queries from the application if you can fetch the needed data in a single query. Always check what queries are executed in your (Rails) log.
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +Database `VIEW` is a pretty useful SQL mechanism. You can use it for:
```suggestion
A database `VIEW` is a pretty useful SQL mechanism. You can use it for:
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +  * hiding complexity of queries
```suggestion
  * hiding the complexity of queries
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +	* reducing complexity by naming a part of the complex query
```suggestion
	* reducing the complexity by naming a part of the complex query
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +  * exposing data subset to the outer world
```suggestion
  * exposing a data subset to the outer world
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Query Examples/09 - LATERAL JOIN.md
> +For calculating the similarity score, use next formula:
```suggestion
For calculating the similarity score, use the following formula:
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +Plain `VIEW` contains only a definition - that means the query would be executed each time you fetch data from the view.
```suggestion
A plain `VIEW` contains only a definition - that means the query will be executed each time you fetch data from the view.
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +The results can be "cached" by using `MATERIALIZED VIEW`. Basically, `MATERIALIZED VIEW` acts as a read-only plain table. To update data in materialized views, use `REFRESH` statement.
```suggestion
The results can be "cached" by using a `MATERIALIZED VIEW`. Basically, a `MATERIALIZED VIEW` acts as a read-only plain table. To update data in materialized views, use the `REFRESH` statement.
```

2022-03-17 15:34 UTC, cukoreva commented on Databases/SQL/Tips & Tricks.md
> +Here's the list of some useful functions and geometry constructors, which can be your starting point when you'll start playing with PostGIS:
```suggestion
Here's the list of some useful functions and geometry constructors, which can be your starting point when you start playing with PostGIS:
```

2022-04-04 07:46 UTC, JureCindro approved these changes

2022-04-04 08:23 UTC, uncoverd approved these changes
I gave this a brief look and I like what I'm seeing 💪 We have a lay of the land and a sizable collection of examples already and I'm guessing more will be added as we find them.

Let's make sure we keep periodically and proactively pinging the team to add interesting examples here 🙏 

Good job @PetarCurkovic, you reduced your job security 😄

2022-04-05 04:59 UTC, nikajukic approved these changes

2022-04-05 07:22 UTC, cilim approved these changes

2022-04-05 07:31 UTC, cukoreva approved these changes

2022-04-05 07:34 UTC, merged